# PitBoss

**The universal governance and certification platform for competitive sim racing leagues.**

PitBoss is a Progressive Web App that brings FIA-grade institutional structure to sim racing. Any league, any rulebook, any series. You upload your documents — PitBoss builds your certification system.

The Truth Racing League (TRL) and World Series Championship (WSC) are the Phase 1 proof of concept. Every role in both institutions must be certified through PitBoss before they can exercise any authority. No exam, no seat.

-----

## What It Does

PitBoss is the sole administrative authority for every league it hosts. It gatekeeps the grid, administers the law, and holds the record of truth.

**Certification Engine**
Every member — drivers, stewards, team principals, BSAC officers, technical directors, broadcast staff — must pass a role-specific exam before they can operate. Exams are AI-generated fresh on every attempt from the official rulebooks. No two exams are identical. Questions are pulled directly from the governing documents and calibrated across three difficulty tiers.

**Document Ingestion**
Drop in any rulebook — PDF, DOCX, TXT, or Markdown — and PitBoss reads it, extracts the rule structure, generates a system prompt, and builds a new exam automatically. New document in, new exam out.

**League Sovereignty**
Every league on PitBoss is a completely separate environment. TRL and WSC certifications, member registries, question banks, and tokens never cross unless explicitly enabled. Each league runs under its own rulebook, its own pass thresholds, and its own admin account.

**Security**
All score calculation is server-side. Certification tokens are server-side. Lockout timers are server-side. Clearing your cache changes nothing. The platform is the only authority.

-----

## Leagues — Phase 1

### Truth Racing League (TRL)

A full FIA-modelled sim racing institution. TRL operates on the Truth and Meritocracy Mandates — your position is earned through certified knowledge, not tenure or relationships.

**Pass mark: 95% across all roles. 94% = Institutional Failure. No rounding.**

|Role                    |Questions|Time  |Practical|
|------------------------|---------|------|---------|
|BSAC Officer            |90       |50 min|+15 min  |
|TRL Steward             |80       |45 min|+15 min  |
|TWG / Technical Director|70       |40 min|—        |
|CRRB Officer            |65       |40 min|—        |
|SLB Officer             |55       |35 min|—        |
|Sporting Director       |50       |30 min|—        |
|Team Principal          |75       |45 min|—        |
|Broadcast Director      |40       |25 min|—        |
|Driver — Elite          |60       |35 min|—        |
|Driver — Apex Pro       |50       |30 min|—        |
|Driver — Apex           |40       |25 min|—        |
|Driver — Academy        |30       |20 min|—        |
|Team Staff              |30       |20 min|—        |

Exam content draws from: TRL Charter v10.0 · BSAC Charter v4.0 · USC v4.0 · USS v4.0 · IRM v2.0 · DDV Regulations v1.1 · DPA v3.0 · P&R Regulations v2.0 · Articles of Expulsion v3.0 · Stewards Charter v3.0 · Attendance Policy v3.0 · and the FIA International Sporting Code, Appendix L, and F1 Sporting Regulations.

### World Series Championship (WSC)

An active sim racing league. Phase 1 certifies WSC Stewards and drivers to a consistent standard using WSC’s own rulebook.

**WSC Steward pass mark: 90%**

|Role         |Questions|Time  |Practical|
|-------------|---------|------|---------|
|WSC Steward  |60       |35 min|+10 min  |
|WSC F1 Driver|50       |30 min|—        |
|WSC F2 Driver|50       |30 min|—        |

A WSC Steward scoring 95%+ on the Stewards exam receives an optional invitation to sit the TRL Stewards exam. This is never mandatory. League sovereignty is maintained — TRL certification does not grant authority in WSC operations and vice versa.

-----

## Exam Mechanics

- Questions are generated by Claude AI (`claude-sonnet-4-20250514`) from the official rulebook content
- Every attempt generates a completely fresh question set — no repeats, no cached banks
- Timer is server-side — cannot be paused, bypassed, or reset by clearing cache
- Timer starts the moment the exam opens
- Exam auto-submits on timer expiry with answers given so far
- Steward exams include a mandatory Practical Incident Scenario after the main exam — this has its own timer that only starts after the main exam is submitted
- Score is calculated server-side only — never client-side
- Failed attempt → 24-hour server-side lockout before retake is available
- Passed attempt → certification token issued, visible on member profile

-----

## Document Ingestion Engine

PitBoss can build an exam from any document you upload. The pipeline:

1. **Upload** — Drop a PDF, DOCX, TXT, or Markdown file into the ingestion panel
1. **Extract** — PDF.js parses real text-layer PDFs page by page. mammoth.js handles DOCX. Plain text reads directly.
1. **Analyse** — Claude reads the extracted content and writes a structured exam system prompt, identifying key articles, rule areas, enforcement mechanisms, and focus topics
1. **Configure** — Set the league, role title, question count, time limit, pass mark, and tier
1. **Generate** — The exam is registered instantly. A new exam card appears in the portal. The exam works identically to all built-in exams.

Generated exams persist within the browser session and can be removed individually or cleared in bulk.

> Scanned/image-only PDFs cannot be extracted — PDF.js requires a text layer. All text-based PDFs, DOCX files, and plain text rulebooks work correctly.

-----

## Technical Stack

|Layer              |Technology                                                           |
|-------------------|---------------------------------------------------------------------|
|Frontend           |HTML / CSS / Vanilla JS — PWA-ready                                  |
|Question generation|Claude API (`claude-sonnet-4-20250514`)                              |
|PDF extraction     |PDF.js 3.11.174 (Cloudflare CDN)                                     |
|DOCX extraction    |mammoth.js 1.6.0 (Cloudflare CDN)                                    |
|Hosting            |GitHub Pages                                                         |
|CORS proxy         |Cloudflare Worker (required for Anthropic API calls from the browser)|

### CORS Proxy Requirement

GitHub Pages serves static files only — it cannot make server-side API calls. All calls to the Anthropic API route through a Cloudflare Worker proxy. Without the proxy, question generation and document analysis will fail with a CORS error.

**Worker setup:**

1. Go to [dash.cloudflare.com](https://dash.cloudflare.com) → Workers & Pages → Create Worker
1. Paste the proxy script (see below)
1. Deploy — copy the worker URL
1. Replace `https://api.anthropic.com/v1/messages` in the portal HTML with your worker URL

```javascript
export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, x-api-key, anthropic-version',
        }
      });
    }

    const body = await request.json();
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify(body),
    });

    const data = await response.json();
    return new Response(JSON.stringify(data), {
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      }
    });
  }
};
```

Set `ANTHROPIC_API_KEY` as a Worker secret in the Cloudflare dashboard.

-----

## Repo Structure

```
pitboss/
├── index.html                  # Main certification portal (all leagues)
├── wsc_stewards_exam.html      # Legacy WSC stewards exam (v1)
├── wsc_f1_driver_exam.html     # Legacy WSC F1 driver exam (v1)
├── wsc_f2_driver_exam.html     # Legacy WSC F2 driver exam (v1)
├── wsc_driver_exam.html        # Legacy WSC driver exam (v1)
├── trl_stewards_exam.html      # Legacy TRL stewards exam (v1)
└── README.md
```

The main `index.html` is the unified Phase 1 portal — all TRL and WSC exams, the document ingestion engine, and all 14 roles in a single file. The legacy exam files remain live for backwards compatibility.

-----

## Roadmap

**Phase 1 — Certification (Current)**
Exam engine, all 14 TRL roles, all 3 WSC roles, document ingestion, PDF/DOCX support.

**Phase 2 — Full PWA**
Supabase backend, persistent member profiles, server-side certification tokens, 24-hour lockout enforcement, Discord OAuth, commissioner dashboard.

**Phase 3 — Incident Management**
Incident ticket filing, stewards workflow, PP tracking, BSAC referral pipeline.

**Phase 4 — Financial Engine**
Salary cap, DDV tracking, contract management, transfer market.

**Phase 5 — Federation Expansion**
Multi-league onboarding, cross-league certification recognition, PitBoss as infrastructure for any sim racing league worldwide — aligned with FIA Appendix E (Esports International Sporting Code, effective January 2026).

-----

## Philosophy

> *“Truth in Meritocracy: Your Seat is Earned, Not Given.”*

PitBoss originated from a real governance failure — a driver was poached, messages were edited, and there was no enforcement mechanism available. A third league was simultaneously observed muting members with no oversight structure.

The answer was not a better Discord server. The answer was institutional infrastructure.

TRL’s governance framework — the Charter, the BSAC, the Stewards Panel, the certification mandate — predates and mirrors what the FIA has now formally codified in Appendix E. PitBoss is the technology layer that makes it operational for community leagues worldwide.

The platform does not care what game you play, what series you model, or how big your league is. You bring your rulebook. PitBoss builds the institution.

-----

*Administered by the TRL Commissioner’s Office — TheTruthExperien*  
*WSC passing results reported to: xjanx07x*
